@startuml
'https://plantuml.com/state-diagram

[*] --> ShowOptions: user appears

ShowOptions --> InsertCard: choose "insert card"
InsertCard --> CheckInserting
CheckInserting --> ShowOptions: card was already inserted
CheckInserting --> Insert: card was not inserted
Insert --> ShowOptions

ShowOptions --> WithdrawCash:choose "withdraw cash"
WithdrawCash --> CheckCardValidation

CheckCardValidation --> CheckPassword: is valid
CheckCardValidation --> ShowOptions: is not valid

state CheckPassword{
ComparingPassword --> WrongPassword
WrongPassword --> ComparingPassword: less than 3 wrong inputs
WrongPassword --> CardBlocking: more than 3 wrong inputs
CardBlocking --> ShowOptions
}

ComparingPassword --> CorrectPassword

CorrectPassword --> EnterCash
EnterCash --> CheckHavingCurrencyOnCard

CheckHavingCurrencyOnCard --> ShowOptions: doesn't have such currency
CheckHavingCurrencyOnCard --> CheckHavingCurrencyInATM: has such currency

CheckHavingCurrencyInATM --> ShowOptions: doesn't have such currency
CheckHavingCurrencyInATM --> UserHasEnough: has such currency

UserHasEnough --> ShowOptions: no
UserHasEnough --> ATMHasEnough: yes

ATMHasEnough --> ShowOptions: no
ATMHasEnough --> CountBanknotes: yes

CountBanknotes --> GiveCash
GiveCash --> ShowOptions

ShowOptions --> RemoveCard
RemoveCard --> CheckForInsertedCard
CheckForInsertedCard --> GiveCardToUser: yes
GiveCardToUser --> ShowOptions
CheckForInsertedCard --> ShowOptions: no

ShowOptions --> Exit: choose "exit"
Exit --> [*]
@enduml